#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<unistd.h>
#include<errno.h>
#include<arpa/inet.h>
#include<sys/stat.h>
#include<fcntl.h>
#include<signal.h>
#include<netinet/in.h>
#include<netinet/ip.h>
#include<sys/socket.h>
#include<pthread.h>
